[package]
name = "high-density-repair03"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[features]
wasm-types = ["dep:tsify", "dep:wasm-bindgen", "math-utils/wasm-types"]

[dependencies]
serde = { version = "1", features = ["derive", "rc"] }
serde_json = { version = "1", features = ["preserve_order", "float_roundtrip"] }
indexmap = { version = "2", features = ["serde"] }
ryu-js = "1.0.3"
wasm-bindgen = { version = "=0.2.128", optional = true }
tsify = { version = "=0.5.8", optional = true, default-features = false, features = ["json"] }
rustc-hash = "2.1.2"
math-utils = { path = "../math-utils" }
json-bindings = { path = "../json-bindings" }
