import { readdir, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import type { ClassTiming, NodeSolverTiming, NodeSummary, SampleSummary, SampleStageSummary, StageSummary } from "./reportTypes"

type BenchmarkSummary = {
  totalMedianMs: number; averageMs: number; p50Ms: number; p95Ms: number;
  baselineRuns: number; samples: SampleSummary[]; stages: StageSummary[];
  sampleStages: SampleStageSummary[]; nodes: NodeSummary[]; classes: ClassTiming[]; nodeSolvers: NodeSolverTiming[];
}

export async function renderReportHtml(outDir: string): Promise<void> {
  const summary = await Bun.file(resolve(outDir, "summary.json")).json() as BenchmarkSummary
  const manifests = (await readdir(outDir)).filter((name) => /^manifest-.*\.json$/.test(name)).sort()
  if (!manifests.length) throw new Error("Missing benchmark environment manifest")
  const manifest = await Bun.file(resolve(outDir, manifests[0]!)).json() as { revision: string; effort: number }
  const detailedReportLink = await Bun.file(resolve(outDir, "detailed-report.md")).exists() ? '<a href="detailed-report.md">Detailed findings and explanations</a>' : ""
  const cpuFile = Bun.file(resolve(outDir, "cpu-summary.json"))
  const cpu = await cpuFile.exists() ? await cpuFile.json() as { functions: Record<string, unknown>[] } : null
  const embeddedSummary = JSON.stringify({ ...summary, cpuFunctions: cpu?.functions ?? [] }).replaceAll("<", "\\u003c")
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SRJ18 · Pipeline9 performance report</title>
<style>
:root{font:15px/1.5 system-ui,sans-serif;color:#192c37;background:#f3f6f5}*{box-sizing:border-box}body{margin:0}main{max-width:1500px;margin:auto;padding:36px 30px}header{border-bottom:2px solid #174e49;padding-bottom:24px}h1{font-size:34px;letter-spacing:-1.2px;margin:8px 0}h2{font-size:23px;margin:30px 0 12px}p{max-width:1000px}.eyebrow{font:12px ui-monospace,monospace;color:#23756c;letter-spacing:2px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.card{background:white;border:1px solid #d6e2dd;border-radius:8px;padding:20px}.card strong{display:block;font-size:28px;color:#174e49}.card span{color:#65777d}a{color:#146b62}nav{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0 16px}button,select,input{font:inherit;padding:9px 12px;border:1px solid #bccfca;border-radius:5px;background:white;color:inherit}button{cursor:pointer}button.active{background:#174e49;color:white}.filters{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:14px}.filters input{min-width:320px;flex:1}.table-wrap{overflow:auto;background:white;border:1px solid #d6e2dd;border-radius:6px}table{border-collapse:collapse;width:100%;font-size:13px}th{background:#e8f0ed;text-align:left;white-space:nowrap;cursor:pointer;position:sticky;top:0}th,td{padding:10px 12px;border-bottom:1px solid #e5ece9}td.numeric{text-align:right;font-variant-numeric:tabular-nums}td:first-child{font-weight:550}tr:hover td{background:#f3f8f6}.bar{display:inline-block;height:9px;background:#3d9b88;margin-right:8px;border-radius:3px;vertical-align:middle}.note{color:#586e73;font-size:13px}.pager{display:flex;gap:12px;align-items:center;margin-top:14px}.legend{background:#e8f0ed;border-left:4px solid #368478;padding:15px 20px}.download{display:flex;gap:18px;flex-wrap:wrap}code{font-family:ui-monospace,monospace;font-size:12px}footer{margin-top:40px;color:#65777d}@media(max-width:800px){main{padding:20px 14px}.cards{grid-template-columns:1fr 1fr}h1{font-size:27px}.filters input{min-width:220px}}
</style></head><body><main>
<header><div class="eyebrow">FRESH BASELINE · UPSTREAM ${manifest.revision.slice(0, 8)} · EFFORT ${manifest.effort}</div><h1>Where Pipeline9 spends its time</h1><p>${summary.samples.length} SRJ18 boards, with repeated baseline timing, individual high-density nodes, nested solver work and CPU profiles. This report uses newly executed runs from a fresh optimization branch.</p><div class="download">${detailedReportLink}<a href="summary.md">Measured tables</a><a href="samples.csv">Sample CSV</a><a href="nodes.csv">Every node CSV</a><a href="classes.csv">Solver CSV</a>${cpu ? '<a href="cpu-functions.csv">Native CPU CSV</a>' : ""}<a href="nodeSolvers.csv">Node × solver CSV</a><a href="${manifests[0]}">Run environment</a></div></header>
<div class="cards"><div class="card"><strong>${(summary.totalMedianMs / 1000).toFixed(2)} s</strong><span>Sum of sample medians</span></div><div class="card"><strong>${(summary.p50Ms / 1000).toFixed(2)} s</strong><span>P50 across boards</span></div><div class="card"><strong>${(summary.p95Ms / 1000).toFixed(2)} s</strong><span>P95 across boards</span></div><div class="card"><strong>${summary.nodes.length.toLocaleString()}</strong><span>High-density routing nodes</span></div></div>
<div class="legend"><b>Read timings correctly.</b> Sample, stage and node durations come from baseline runs with outer stage/node timing. Solver self time comes from the detailed run and includes instrumentation overhead. Self times exclude nested measured calls; inclusive parent and child times overlap. A constructed candidate may never run because another candidate wins. Sort any column by clicking its heading; click a node ID to see that node’s solvers.</div>
<nav id="tabs"></nav><div class="filters"><select aria-label="Sample" id="sample"><option value="">All samples</option></select><select aria-label="Stage" id="stage"><option value="">All stages</option></select><input aria-label="Search rows" id="search" placeholder="Search node ID, solver or status…"></div>
<h2 id="title"></h2><p id="description" class="note"></p><div class="table-wrap"><table><thead id="head"></thead><tbody id="body"></tbody></table></div><div class="pager"><button id="previous">Previous</button><span id="count"></span><button id="next">Next</button></div>
<footer>Baseline runs: ${summary.baselineRuns}; ${summary.samples.filter((sample) => sample.solved).length}/${summary.samples.length} boards solved in every baseline run. Dataset timing includes time to failure. P50 is the median of sample medians; P95 uses nearest rank. Per-stage medians need not sum exactly to the median total. Detailed raw JSON and per-record CSV files are gzip-compressed in the detailed and solver-records folders.</footer>
</main><script>
const report=${embeddedSummary};
const views={samples:{title:'Board runtimes',description:'Seconds are baseline medians with observed minimum and maximum. The output parity column compares all baseline outputs and the detailed output.',columns:['sampleId','medianMs','minMs','maxMs','solved','drcErrors','outputParity','outcomeParity','overheadRatio','highDensityNodes']},stages:{title:'Every pipeline stage',description:'Stage totals sum each board’s median. Full stage timing includes input preparation, construction, step execution and completion callbacks.',columns:['stage','durationMs','sharePercent','maxSample','maxSampleMs','internalDurationMs','omittedByInternalMs']},sampleStages:{title:'Stages by board',description:'Each stage on each sample. Not-reached stages show zero measured time and an explicit status.',columns:['sampleId','stage','durationMs','sharePercent','status','steps','internalDurationMs','omittedByInternalMs']},nodes:{title:'Every high-density node',description:'Baseline timing includes preparation and all solver attempts for that node. Click its ID to inspect the nested solvers.',columns:['sampleId','nodeId','medianMs','winningSolver','ports','connections','width','height','nodePf','resizeCount','totalRecordedGrowthAttempts','regionalRecovery','status']},classes:{title:'Nested solvers by sample',description:'Self seconds are measured in the detailed run. Records include separate construction and lifecycle contexts when a constructor calls a measured method before returning. Construction counts count instrumented new expressions.',columns:['sampleId','stage','solver','selfMs','constructionSelfMs','constructions','stepCalls','iterations','solved','failed','unfinished','zeroStepRecords','cacheHits']},nodeSolvers:{title:'Nested solvers by node',description:'Detailed self time attributed to node IDs, inherited by child solvers. Use the sample and stage filters to inspect a particular part of the pipeline.',columns:['sampleId','nodeId','stage','solver','selfMs','constructionSelfMs','constructions','stepCalls','iterations']}};
if(report.cpuFunctions.length)views.cpuFunctions={title:'Native CPU functions',description:'Separate original-source sampling run. Routing self time selects sampled stacks with a BaseSolver step ancestor. Inclusive times overlap; profiler sampling affects runtime. Times are not baseline latency.',columns:['function','file','line','routingSelfMs','routingInclusiveMs','selfMs','inclusiveMs','routingSamples','samples']};
const labels={function:'Function',file:'File',line:'Line',routingSelfMs:'Routing self (s)',routingInclusiveMs:'Routing inclusive (s)',inclusiveMs:'Process inclusive (s)',routingSamples:'Routing samples',samples:'Process samples',sampleId:'Sample',medianMs:'Median (s)',minMs:'Min (s)',maxMs:'Max (s)',solved:'Solved',drcErrors:'DRC errors',outputParity:'Output parity',outcomeParity:'Outcome parity',steps:'Pipeline steps',overheadRatio:'Profiler ×',highDensityNodes:'Nodes',stage:'Stage',durationMs:'Total (s)',sharePercent:'Share %',maxSample:'Slowest sample',maxSampleMs:'Its time (s)',internalDurationMs:'Internal timer (s)',omittedByInternalMs:'Timer delta (s)',nodeId:'Node',winningSolver:'Winner',ports:'Ports',connections:'Connections',width:'Width mm',height:'Height mm',nodePf:'Node Pf',resizeCount:'Regular growths',totalRecordedGrowthAttempts:'All recorded growths',regionalRecovery:'Regional recovery',status:'Status',solver:'Solver',selfMs:'Self (s)',constructionSelfMs:'Constructor self (s)',constructions:'Constructed',stepCalls:'step calls',iterations:'Iterations',failed:'Failed records',unfinished:'Unfinished records',zeroStepRecords:'Zero-step records',cacheHits:'Cache hits'};
let view='stages',sort='durationMs',direction=-1,page=0,selectedNodeId=null;const pageSize=100;
const byId=id=>document.getElementById(id);const escape=text=>String(text).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
for(const sample of report.samples)byId('sample').add(new Option(sample.sampleId,sample.sampleId));
for(const stage of report.stages)byId('stage').add(new Option(stage.stage,stage.stage));
byId('tabs').innerHTML=Object.entries(views).map(([key,config])=>'<button data-view="'+key+'">'+config.title+'</button>').join('');
function render(){const config=views[view];byId('sample').disabled=view==='stages'||view==='cpuFunctions';byId('stage').disabled=view==='cpuFunctions';byId('title').textContent=config.title;byId('description').textContent=config.description;document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));let rows=report[view].filter(row=>(!selectedNodeId||row.nodeId===selectedNodeId)&&(!byId('sample').value||!row.sampleId||row.sampleId===byId('sample').value)&&(!byId('stage').value||!row.stage||row.stage===byId('stage').value)&&Object.values(row).join(' ').toLowerCase().includes(byId('search').value.toLowerCase()));rows.sort((a,b)=>{const left=a[sort],right=b[sort];return direction*(typeof left==='number'&&typeof right==='number'?left-right:String(left).localeCompare(String(right)))});page=Math.min(page,Math.max(0,Math.ceil(rows.length/pageSize)-1));byId('head').innerHTML='<tr>'+config.columns.map(column=>'<th data-column="'+column+'">'+escape(labels[column]||column)+(sort===column?(direction===-1?' ↓':' ↑'):'')+'</th>').join('')+'</tr>';byId('body').innerHTML=rows.slice(page*pageSize,(page+1)*pageSize).map(row=>'<tr>'+config.columns.map(column=>{let field=row[column];let content=field===null||field===undefined?'—':typeof field==='number'?(column.endsWith('Ms')?(field/1000).toFixed(4):Number.isInteger(field)?field.toLocaleString():field.toFixed(3)):escape(field);if(column==='nodeId'&&view==='nodes')content='<a href="#" data-node="'+escape(field)+'" data-sample="'+escape(row.sampleId)+'">'+content+'</a>';if(column==='sharePercent')content='<span class="bar" style="width:'+Math.min(150,field*3)+'px"></span>'+content;return '<td class="'+(typeof field==='number'?'numeric':'')+'">'+content+'</td>'}).join('')+'</tr>').join('');byId('count').textContent=rows.length?'Rows '+(page*pageSize+1)+'–'+Math.min((page+1)*pageSize,rows.length)+' of '+rows.length.toLocaleString():'No matching rows';byId('previous').disabled=page===0;byId('next').disabled=(page+1)*pageSize>=rows.length;}
byId('tabs').onclick=event=>{const button=event.target.closest('[data-view]');if(!button)return;view=button.dataset.view;selectedNodeId=null;sort=(view==='stages'||view==='sampleStages')?'durationMs':view==='samples'||view==='nodes'?'medianMs':view==='cpuFunctions'?'routingSelfMs':'selfMs';direction=-1;page=0;render()};
byId('head').onclick=event=>{const heading=event.target.closest('[data-column]');if(!heading)return;direction=sort===heading.dataset.column?-direction:-1;sort=heading.dataset.column;render()};
byId('body').onclick=event=>{const link=event.target.closest('[data-node]');if(!link)return;event.preventDefault();view='nodeSolvers';sort='selfMs';direction=-1;page=0;byId('sample').value=link.dataset.sample;byId('stage').value='highDensityRouteSolver';byId('search').value=link.dataset.node;selectedNodeId=link.dataset.node;render()};
for(const id of ['sample','stage','search'])byId(id).addEventListener('input',()=>{page=0;selectedNodeId=null;render()});byId('previous').onclick=()=>{page--;render()};byId('next').onclick=()=>{page++;render()};render();
</script></body></html>`
  await writeFile(resolve(outDir, "report.html"), html)
}
