[package]
name = "json-bindings"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "float_roundtrip"] }
tsify = { version = "=0.5.8", default-features = false, features = ["json"] }
wasm-bindgen = "=0.2.128"
ryu-js = "1.0.3"
